FROM python:3.8-slim

# streamlit-specific commands
RUN mkdir -p ~/.streamlit
RUN bash -c 'echo -e "\
    [server]\n\
    headless = true\n\
    port = $PORT\n\
    enableCORS = false\n\
    " > ~/.streamlit/config.toml'

# copy over and install packages
COPY requirements_web.txt ./app/requirements_web.txt
RUN pip3 install -r app/requirements_web.txt

# copy workspace over to /app
COPY . /app
WORKDIR /app

CMD ["sh", "-c", "streamlit run --server.port $PORT app.py"]
